server:
  port: 80
  servlet:
    context-path: /sso-app/
spring:
  application:
    name: harry-boot-sso-app
  redis:
    host: 192.168.148.131
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      primary: master
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: 'select 1'
      datasource:
        master:
          url: jdbc:mysql://192.168.148.131:3306/harry?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
          username: root
          password: Abcd-1234
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource #Hikaricp
        slave:
          url: jdbc:mysql://192.168.148.131:3306/db_harry?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
          username: root
          password: Abcd-1234
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource #Druid

#Mybatis
mybatis-plus:
  config-location: classpath:/mybatis/mybatis-config.xml

logging:
  level:
    com.baomidou: debug

security:
  base:
    enabled: true
  user:
    name: admin
    password: 123456
harry:
  base:
    security:
      oauth2:
        storeType: jwt
      browser:
        loginType: REDIRECT
        signOutUrl: /signOut.html
      social:
        open: false
    datasource:
      mapperLocation: com.harry.sso.app.domain.mapper
    swagger:
      title: HARRY BOOT SSO
      description: 统一认证
      version: v1.0.0
      termsOfServiceUrl: http://localhost${server.servlet.context-path}
      base-Package: com.harry.sso.app.domain.rest
      authorization:
        name: BearerToken
        authServers: http://localhost${server.servlet.context-path}
        authorizationScopeList[0]:
          scope: user_info
          description: read all resources
